apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: rabbitmq
  template:
    metadata:
      labels:
        components: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:4.2.2-management-alpine
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        env:
          - name: SEED_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: SEED_USERNAME
          - name: SEED_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: SEED_USER_PASSWORD
        ports:
        - containerPort: 5672
        volumeMounts:
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
    